import 'server-only';
import postgres from 'postgres';

export type ReviewAnswer = 'existing_job'|'create_job'|'canceled'|'different_work'|'not_sure'|'keep_active';
export type ReviewCandidate = { jobId?:string; jobNumber:string; amount?:number; status?:string; createdAt?:string; scheduledAt?:string; address?:string; scope?:string; evidence?:string[]; contradictions?:string[] };
export type ReviewCase = { id:string; queue:'reconciliation'|'cleanup'; sortOrder:number; estimateId:string; estimateNumber:string; customer:string; address?:string; amount?:number; createdAt?:string; updatedAt?:string; status?:string; scope?:string; likelyAnswer?:ReviewAnswer; likelyReason?:string; question:string; candidates:ReviewCandidate[]; sourceCheckedAt:string; sourceRefreshStatus?:'current'|'seeded'|'failed'; decision?:ReviewDecision|null };
export type ReviewDecision = { caseId:string; answer:ReviewAnswer; note?:string; actor:string; version:number; answeredAt:string };
const databaseUrl=process.env.DATABASE_URL||process.env.Database_url;
let client:postgres.Sql|null=null; let ready:Promise<void>|null=null;
function db(){if(!databaseUrl)throw new Error('DATABASE_URL is required.');client??=postgres(databaseUrl,{max:5,ssl:'require'});return client;}
async function schema(){ready??=(async()=>{const sql=db();await sql`create table if not exists morgan_door_review_cases(id text primary key,queue text not null,sort_order integer not null,payload jsonb not null,source_checked_at timestamptz not null,updated_at timestamptz not null)`;await sql`create table if not exists morgan_door_review_decisions(case_id text primary key references morgan_door_review_cases(id),answer text not null,note text,actor text not null,version integer not null default 1,answered_at timestamptz not null)`;await sql`create index if not exists morgan_door_review_queue_idx on morgan_door_review_cases(queue,sort_order)`;})();await ready;}
function decision(row:Record<string,unknown>|undefined):ReviewDecision|null{return row?.answer?{caseId:String(row.id),answer:String(row.answer) as ReviewAnswer,note:row.note?String(row.note):undefined,actor:String(row.actor),version:Number(row.version),answeredAt:new Date(row.answered_at as string|Date).toISOString()}:null;}
function map(row:Record<string,unknown>):ReviewCase{const payload=row.payload as Omit<ReviewCase,'decision'>;return {...payload,sourceCheckedAt:new Date(row.source_checked_at as string|Date).toISOString(),decision:decision(row)};}
export async function listCases(){await schema();const rows=await db()`select c.*,d.answer,d.note,d.actor,d.version,d.answered_at from morgan_door_review_cases c left join morgan_door_review_decisions d on d.case_id=c.id order by c.queue desc,c.sort_order,c.id`;return rows.map(r=>map(r as Record<string,unknown>));}
export async function getCase(id:string){await schema();const rows=await db()`select c.*,d.answer,d.note,d.actor,d.version,d.answered_at from morgan_door_review_cases c left join morgan_door_review_decisions d on d.case_id=c.id where c.id=${id}`;return rows[0]?map(rows[0] as Record<string,unknown>):null;}
const answers=new Set<ReviewAnswer>(['existing_job','create_job','canceled','different_work','not_sure','keep_active']);
export async function saveDecision(caseId:string,answer:ReviewAnswer,note:string,expectedVersion:number){if(!answers.has(answer))throw new Error('Invalid answer');if(note.length>1000)throw new Error('Note is too long');if(!Number.isInteger(expectedVersion)||expectedVersion<0)throw new Error('Invalid answer version');await schema();const sql=db();return sql.begin(async tx=>{const found=await tx`select id from morgan_door_review_cases where id=${caseId}`;if(!found.length)throw new Error('Case not found');const now=new Date();const rows=await tx`insert into morgan_door_review_decisions(case_id,answer,note,actor,version,answered_at) values(${caseId},${answer},${note||null},'Braxton',1,${now}) on conflict(case_id) do update set answer=excluded.answer,note=excluded.note,actor=excluded.actor,version=morgan_door_review_decisions.version+1,answered_at=excluded.answered_at where morgan_door_review_decisions.version=${expectedVersion} returning *`;if(!rows.length){const e=new Error('This answer changed in another session. Reload before saving again.') as Error&{status?:number};e.status=409;throw e;}return decision({...rows[0],id:caseId})!;});}
export async function seedCases(cases:Array<Omit<ReviewCase,'decision'>>){await schema();const sql=db();for(const item of cases){const{sourceCheckedAt,...payload}=item;await sql`insert into morgan_door_review_cases(id,queue,sort_order,payload,source_checked_at,updated_at) values(${item.id},${item.queue},${item.sortOrder},${sql.json(payload as never)},${sourceCheckedAt},now()) on conflict(id) do update set queue=excluded.queue,sort_order=excluded.sort_order,payload=excluded.payload,source_checked_at=excluded.source_checked_at,updated_at=now()`;}return {seeded:cases.length};}
export async function updateCaseSource(id:string,payload:Omit<ReviewCase,'decision'|'sourceCheckedAt'>,checkedAt:string){await schema();await db()`update morgan_door_review_cases set payload=${db().json(payload as never)},source_checked_at=${checkedAt},updated_at=now() where id=${id}`;}
