import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

export const metadata: Metadata = { title: 'Terms of Service | Stoke AI', description: 'Terms governing Stoke AI services and client text communications.' };

export default function TermsPage() {
  return <main className="min-h-screen bg-[#0d0d0d] text-white"><div className="mx-auto max-w-4xl px-5 py-8 sm:px-8 sm:py-12">
    <header className="mb-10 flex items-center justify-between border-b border-white/10 pb-6"><Link href="/" className="block w-40 sm:w-48"><Image src="/logo.png" alt="Stoke AI" width={500} height={170} className="h-auto w-full" /></Link><Link href="/sms-consent" className="text-sm font-bold text-orange-300 hover:text-orange-200">SMS consent</Link></header>
    <p className="text-sm font-bold uppercase tracking-[0.2em] text-orange-300">Legal</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Terms of Service</h1><p className="mt-4 text-gray-400">Effective July 14, 2026</p>
    <div className="mt-10 space-y-9 text-base leading-7 text-gray-300">
      <section><h2 className="text-xl font-black text-white">Agreement</h2><p className="mt-2">These Terms govern your use of websites, client workspaces, communication tools, and services provided by JHEKOO LLC doing business as Stoke AI (“Stoke AI”). By using our services, you agree to these Terms and our <Link href="/privacy" className="text-orange-300 underline">Privacy Policy</Link>. A separate written client agreement controls if it conflicts with these general Terms.</p></section>
      <section><h2 className="text-xl font-black text-white">Services</h2><p className="mt-2">Stoke AI provides business systems, automation, implementation, advisory, support, and related client services. Scope, timing, responsibilities, fees, and deliverables may be defined in a separate agreement or approved project plan.</p></section>
      <section className="rounded-2xl border border-orange-400/20 bg-orange-500/[0.06] p-5 sm:p-6"><h2 className="text-xl font-black text-white">Stoke AI Client Communications SMS program</h2><div className="mt-3 space-y-3"><p>After you provide express consent, Stoke AI may send conversational text messages about active services, project updates, questions, requested information, scheduling, and account support.</p><ul className="list-disc space-y-2 pl-5"><li>Message frequency varies based on your active work and requests.</li><li>Message and data rates may apply.</li><li>Reply <strong className="text-white">STOP</strong> to unsubscribe at any time.</li><li>Reply <strong className="text-white">HELP</strong> for help, or contact automate@stoke-ai.com or +1 (208) 573-7224.</li><li>Consent to receive text messages is not a condition of purchase.</li><li>Carriers are not liable for delayed or undelivered messages.</li></ul><p>We may change the sending number or messaging provider while preserving these program terms. See our <Link href="/privacy" className="font-bold text-orange-300 underline">Privacy Policy</Link> for how mobile information and consent records are handled.</p></div></section>
      <section><h2 className="text-xl font-black text-white">Your responsibilities</h2><p className="mt-2">You agree to provide accurate information, protect account access, use services lawfully, and avoid submitting content that infringes rights, contains malicious code, or creates unreasonable security or operational risk.</p></section>
      <section><h2 className="text-xl font-black text-white">Intellectual property</h2><p className="mt-2">Each party retains ownership of materials, systems, trademarks, and intellectual property it owned before an engagement. Ownership and licensing of custom deliverables are governed by the applicable client agreement.</p></section>
      <section><h2 className="text-xl font-black text-white">Third-party services</h2><p className="mt-2">Our services may connect with third-party platforms. Stoke AI is not responsible for third-party outages, policy changes, security, or terms, though we will use reasonable care when configuring integrations.</p></section>
      <section><h2 className="text-xl font-black text-white">Disclaimers and limitation of liability</h2><p className="mt-2">Services are provided on an “as available” basis except as expressly stated in a written agreement. To the extent permitted by law, Stoke AI disclaims implied warranties and will not be liable for indirect, incidental, special, consequential, or punitive damages. Any direct liability is limited to amounts paid for the affected services during the three months before the event giving rise to the claim, unless a written agreement or applicable law requires otherwise.</p></section>
      <section><h2 className="text-xl font-black text-white">Governing law</h2><p className="mt-2">These Terms are governed by the laws of the State of Idaho, without regard to conflict-of-law rules. Venue for disputes will lie in Idaho unless the parties agree otherwise in writing.</p></section>
      <section><h2 className="text-xl font-black text-white">Changes and contact</h2><p className="mt-2">We may update these Terms as our services change. Continued use after an update means you accept the revised Terms. Questions may be sent to automate@stoke-ai.com.</p><p className="mt-4">JHEKOO LLC dba Stoke AI<br />450 W 90 N<br />Burley, ID 83318<br /><a className="text-orange-300 underline" href="mailto:automate@stoke-ai.com">automate@stoke-ai.com</a><br /><a className="text-orange-300 underline" href="tel:+12085737224">+1 (208) 573-7224</a></p></section>
    </div>
    <footer className="mt-12 flex gap-5 border-t border-white/10 pt-6 text-sm text-gray-400"><Link href="/" className="hover:text-orange-300">Home</Link><Link href="/privacy" className="hover:text-orange-300">Privacy Policy</Link><Link href="/sms-consent" className="hover:text-orange-300">SMS consent</Link></footer>
  </div></main>;
}
